import '../../../core/api/api_client.dart';
import '../../../core/mock/models.dart';

/// Backend-facing surface for the wallet feature.
///
/// **Squad / GTBank flows server-side only.** The mobile client never
/// talks to Squad directly — that's the backend's job. The client
/// hands the backend an amount; the backend's Squad GTBank
/// integration moves the money. So:
///
/// - The withdrawal calls (`previewWithdrawal`, `submitWithdrawal`)
///   take **only an amount**. There is no "select destination" or
///   "link external bank" step on the withdraw page — the backend
///   already knows where the worker's wallet routes via Squad.
/// - The bank-account methods further down (`fetchMyAccounts`, etc.)
///   exist for the *separate* "Linked accounts" surface accessible
///   from the profile tab. They are **not** required for withdrawal.
///
/// Specs: `11_withdraw.md` + `12_bank_accounts.md`. The withdraw
/// preview / submit DTOs in the OpenAPI doc still mention
/// `bank_account_id`; the backend keeps that field optional and falls
/// back to the worker's Squad-managed wallet when it's omitted.
class WalletRepository {
  WalletRepository({required ApiClient client}) : _client = client;
  final ApiClient _client;

  // ---- withdrawals (Squad GTBank, server-side) ---------------------

  /// `GET /wallet/withdrawals/preview` — fee + ETA + masked
  /// destination, computed server-side from the worker's wallet
  /// routing. Mobile renders the result as a confirmation row before
  /// the user taps "Withdraw".
  Future<WithdrawalPreview> previewWithdrawal({
    required int amount,
  }) async {
    final json = await _client.get(
      '/wallet/withdrawals/preview',
      authenticated: true,
      query: <String, String>{
        'amount': amount.toString(),
      },
    );
    return WithdrawalPreview.fromJson(json);
  }

  /// `POST /wallet/withdrawals` — kicks off a Squad transfer on the
  /// backend. The response carries the freshly-created [Transaction]
  /// row (so the wallet UI can refresh instantly without re-fetching
  /// `/me`) and the new `walletBalanceAfter`.
  ///
  /// [clientWithdrawalId] is a per-attempt UUID generated by the
  /// caller. It's used as the `Idempotency-Key` suffix; a retry of
  /// the same logical attempt (network blip, app restart) reuses the
  /// same key so the server returns the existing transaction instead
  /// of double-debiting.
  Future<WithdrawalResult> submitWithdrawal({
    required int amount,
    required String clientWithdrawalId,
  }) async {
    final json = await _client.post(
      '/wallet/withdrawals',
      authenticated: true,
      idempotent: true,
      idempotencyAction: 'withdraw:$clientWithdrawalId',
      body: <String, dynamic>{
        'amount': amount,
      },
    );
    return WithdrawalResult(
      transaction: Transaction.fromJson(
        json['transaction'] as Map<String, dynamic>,
      ),
      walletBalanceAfter:
          (json['wallet_balance_after'] as num?)?.toInt() ?? 0,
    );
  }

  // ---- linked-account management (separate surface) ----------------
  //
  // Used by the "Linked accounts" / link-bank screen in the profile
  // tab. NOT used by the withdraw flow — Squad handles withdrawal
  // routing server-side. Kept here so the profile feature still has
  // a place to call into when the user explicitly wants to attach
  // (or audit) a bank account on file.

  Future<List<Bank>> fetchSupportedBanks() async {
    final json = await _client.get('/banks');
    return (json['items'] as List? ?? const <dynamic>[])
        .whereType<Map<String, dynamic>>()
        .map(Bank.fromJson)
        .toList(growable: false);
  }

  Future<List<BankAccount>> fetchMyAccounts() async {
    final json = await _client.get(
      '/me/bank-accounts',
      authenticated: true,
    );
    return (json['items'] as List? ?? const <dynamic>[])
        .whereType<Map<String, dynamic>>()
        .map(BankAccount.fromJson)
        .toList(growable: false);
  }

  Future<String> resolveAccountName({
    required String bankCode,
    required String accountNumber,
  }) async {
    final json = await _client.post(
      '/me/bank-accounts/resolve',
      authenticated: true,
      body: <String, dynamic>{
        'bank_code': bankCode,
        'account_number': accountNumber,
      },
    );
    return json['account_name'] as String;
  }

  Future<BankAccount> linkAccount({
    required String bankCode,
    required String accountNumber,
    required String accountName,
    bool setAsDefault = true,
  }) async {
    final json = await _client.post(
      '/me/bank-accounts',
      authenticated: true,
      idempotent: true,
      // Same (bank_code, account_number) submitted twice resolves to
      // the same row server-side via 409 ALREADY_LINKED; the
      // idempotency key adds a transport-layer guard for retries of
      // the same submit attempt.
      idempotencyAction: 'link-bank:$bankCode:$accountNumber',
      body: <String, dynamic>{
        'bank_code': bankCode,
        'account_number': accountNumber,
        'account_name': accountName,
        'set_as_default': setAsDefault,
      },
    );
    return BankAccount.fromJson(json);
  }

  Future<List<BankAccount>> setDefault(String id) async {
    final json = await _client.post(
      '/me/bank-accounts/$id/default',
      authenticated: true,
    );
    return (json['items'] as List? ?? const <dynamic>[])
        .whereType<Map<String, dynamic>>()
        .map(BankAccount.fromJson)
        .toList(growable: false);
  }

  Future<void> removeAccount(String id) async {
    await _client.delete(
      '/me/bank-accounts/$id',
      authenticated: true,
    );
  }
}

class WithdrawalPreview {
  const WithdrawalPreview({
    required this.amount,
    required this.fee,
    required this.amountCredited,
    required this.estimatedArrival,
    required this.estimatedArrivalAt,
    required this.destinationBank,
    required this.destinationLast4,
    required this.destinationAccountName,
  });

  final int amount;
  final int fee;
  final int amountCredited;
  final String estimatedArrival;
  final DateTime estimatedArrivalAt;

  /// Backend-resolved destination — the Squad-managed bank the funds
  /// land in. Display-only; the client never selects it.
  final String destinationBank;
  final String destinationLast4;
  final String destinationAccountName;

  factory WithdrawalPreview.fromJson(Map<String, dynamic> json) {
    final dest = json['destination'] as Map<String, dynamic>;
    return WithdrawalPreview(
      amount: (json['amount'] as num).toInt(),
      fee: (json['fee'] as num?)?.toInt() ?? 0,
      amountCredited: (json['amount_credited'] as num).toInt(),
      estimatedArrival: json['estimated_arrival'] as String? ?? '',
      estimatedArrivalAt:
          DateTime.parse(json['estimated_arrival_at'] as String).toUtc(),
      destinationBank: dest['bank_name'] as String,
      destinationLast4: dest['account_number_last4'] as String,
      destinationAccountName: dest['account_name'] as String,
    );
  }
}

class WithdrawalResult {
  const WithdrawalResult({
    required this.transaction,
    required this.walletBalanceAfter,
  });
  final Transaction transaction;
  final int walletBalanceAfter;
}
